cache: pip
language: python

python:
  - "2.7"

install:
  - pip install sphinx
  - pip install sphinx_rtd_theme

env:
  matrix:
    - TEST_DIR=en
    - TEST_DIR=ko

before_script:
  - cd $TEST_DIR

after_script:
  - cd ..

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      script: make html
    - stage: test
      script: make linkcheck