cache: pip
language: python

python:
  - "2.7"

install:
  - pip install sphinx
  - pip install sphinx_rtd_theme

env:
  jobs:
    - COMMAND=html
  matrix:
    - TEST_DIR=en
    - TEST_DIR=ko

before_script:
  - cd $TEST_DIR

script:
  - make $COMMAND

after_script:
  - cd ..

jobs:
  include:
    - stage: linkcheck
      env: COMMAND=linkcheck