cache: pip
language: python

python:
  - "2.7"

install:
  - pip install sphinx
  - pip install sphinx_rtd_theme

before_script:
  - cd $TEST_DIR

after_script:
  - cd ..

jobs:
  include:
    env:
      matrix:
        - TEST_DIR=en
        - TEST_DIR=ko
    - stage: test
      name: "build"
      script: make html
    - script: make linkcheck
      name: "linkcheck"