cache: pip
language: python

python:
  - "2.7"

install:
  - pip install sphinx
  - pip install sphinx_rtd_theme

env:
  matrix:
    - TEST_DIR=en COMMAND=html
    - TEST_DIR=ko COMMAND=html

before_script:
  - cd $TEST_DIR

script:
  - make $COMMAND

after_script:
  - cd ..

jobs:
  include:
    - stage: linkcheck_english
      env: TEST_DIR=en COMMAND=linkcheck
    - stage: linkcheck_korean
      env: TEST_DIR=ko COMMAND=linkcheck