cache: pip
language: python

python:
  - "2.7"

install:
  - pip install sphinx
  - pip install sphinx_rtd_theme

before_script:
  - cd $TEST_DIR

script:
  - make $COMMAND

after_script:
  - cd ..

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      env: TEST_DIR=en COMMAND=html
    - stage: build
      env: TEST_DIR=ko COMMAND=html
    - stage: test
      env: TEST_DIR=en COMMAND=linkcheck
    - stage: test
      env: TEST_DIR=ko COMMAND=linkcheck