cache: pip
language: python

python:
  - "2.7"

before_script:
  - cd $TEST_DIR

script:
  - make $COMMAND

after_script:
  - cd ..

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      name: "Build English Manaul"
      env: TEST_DIR=en COMMAND=html
    - stage: build
      name: "Build Korean Manaul"
      env: TEST_DIR=ko COMMAND=html
    - stage: test
      name: "Test English Manaul"
      env: TEST_DIR=en COMMAND=linkcheck
      install: skip
    - stage: test
      name: "Test Korean Manaul"
      env: TEST_DIR=ko COMMAND=linkcheck
      install: skip